spring:
    application:
        name: BoGo

    jpa:
        database: mysql
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO:validate}
        open-in-view: false
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_NAME}
        username: ${DB_USERNAME:root}
        password: ${PASSWORD}

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${SPRING_MAIL_SMTP_AUTH}
                    starttls:
                        enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
                        required: ${SPRING_MAIL_SMTP_STARTTLS_REQUIRED}
                    connectiontimeout: ${SPRING_MAIL_SMTP_CONNECTIONTIMEOUT}
                    timeout: ${SPRING_MAIL_SMTP_TIMEOUT}
                    writetimeout: ${SPRING_MAIL_SMTP_WRITETIMEOUT}
            auth-code-expiration-millis: ${AUTH_CODE_EXPIRATION_MILLIS}